name: Wait Timer
description: test_js_action

inputs:
  milliseconds:
    description: Duration to wait
    required: true

outputs:
  time:
    description: Current time

runs:
  using: node24
  main: dist/index.js