name: Test
on:
  workflow_dispatch:

jobs:
  Test_yml:
    runs-on: ubuntu-latest
    steps:  
      - name: Generate_tag
        id : foo
        run: |
          echo "image_tag=v2.5.5">>$GITHUB_OUTPUT
      - name: Build image
        run: |
          docker build -t myapp:${{ steps.foo.outputs.image-version }} .
      - name: Varify image
        run: |
          echo "Everything work well"

        