name: Test_Error
on:
  workflow_dispatch:
    
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "::group::Install Dependencies!!!"
         echo "Installing package A"
         echo "Installing package B"
         echo "::endgroup::"
